FROM gabrieletassoni/thecore-common:latest

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com \
    && apt-get update && apt-get -y install \
        git-flow \
        graphviz \
    # Update
    && apt-get -y dist-upgrade --no-install-recommends \
    # Clean up
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Add at least a version of rails to work with
RUN gem install rails -v '~> 6.1.0'

# Add to the container thecore specific scripts
RUN mkdir -p /etc/thecore/templates /etc/thecore/repos.conf.d

COPY scripts/ /usr/bin/
COPY bin/increment_version.sh /usr/bin/increment_version.sh
COPY templates /etc/thecore/templates
COPY thor_definitions/ /etc/thecore/
COPY repos /etc/thecore/repos.conf.d
COPY docker /etc/thecore/docker

# Creating the git clones of thecore gems.
# Useful to have them already inside the dev environment if the need to customize them arises.
# Otherwise the gem installed ones will suffice to the needs of thecore development.
RUN useradd -ms /bin/bash vscode \
    && usermod -aG sudo vscode \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER vscode

RUN mkdir ~/.thor \
    && cp /etc/thecore/thecore_generate.thor ~/.thor/a84ebaa152a909f88944fc7354130e94 \
    && cp /etc/thecore/thor.yml ~/.thor/thor.yml \
    && echo 'export PS1="\e[32m\u\e[0m ► \e[96m\W\e[0m [\e[31m\$(git rev-parse --abbrev-ref HEAD)\e[0m:\e[33m\$(git describe --tags --abbrev=0)\e[0m] \$ "'  >> ~/.bashrc \
    && echo '/usr/bin/thecore' >> ~/.bashrc \
    && echo 'export APPBIN=/workspaces/project/app/bin'  >> ~/.bashrc \
    && echo 'export CODEBIN=$(find $HOME/.vscode-server/bin/* -maxdepth 1 -mindepth 1 -name bin)'  >> ~/.bashrc \
    && echo 'export PATH=$GEM_HOME/bin:$PATH:$APPBIN:$CODEBIN' >> ~/.bashrc \
    && tail ~/.bashrc \
    && bundle config set path /workspaces/project/app/vendor/bundle

WORKDIR /workspaces/project
