ARG THECORE_VERSION
FROM gabrieletassoni/thecore-common:${THECORE_VERSION}

# Install base packages and latest debian keyrings
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update && apt-get -y install --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    sudo \
    rsync \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Setup Docker repository
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update && apt-get -y install --no-install-recommends \
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
        git-flow \
        graphviz \
        python3-pip \
    # Clean up
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* 

# Add at least a version of rails to work with
RUN gem install rails:'~> 7.1.2' foreman rufo

RUN mkdir -p /usr/local/bundle \
    && chmod -R 1777 /usr/local/bundle

RUN mkdir -p /etc/thecore/templates /etc/thecore/repos.conf.d
COPY bin/increment_version.sh /usr/bin/increment_version.sh
COPY repos /etc/thecore/repos.conf.d
COPY localdockerbuild /etc/thecore/localdockerbuild
# Creating the git clones of thecore gems.
# Useful to have them already inside the dev environment if the need to customize them arises.
# Otherwise the gem installed ones will suffice to the needs of thecore development.
RUN useradd -ms /bin/bash vscode \
    && usermod -aG sudo vscode \
    && usermod -aG docker vscode \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER vscode

RUN echo 'export PS1="\e[32m\u\e[0m ► \e[96m\W\e[0m [\e[31m\$(git rev-parse --abbrev-ref HEAD 2>/dev/null)\e[0m:\e[33m\$(git describe --tags --abbrev=0 2>/dev/null)\e[0m] \$ "' >> ~/.bashrc \
    && echo '/usr/bin/thecore' >> ~/.bashrc \
    && echo 'export APPBIN=/workspaces/project/backend/bin' >> ~/.bashrc \
    && echo 'export COMPOSE_PROJECT_NAME=thecore_test' >> ~/.bashrc \
    && echo 'export CODEBIN=$(find $HOME/.vscode-server/bin/* -maxdepth 1 -mindepth 1 -name bin)' >> ~/.bashrc \
    && echo 'export PATH=$GEM_HOME/bin:$PATH:$APPBIN:$CODEBIN' >> ~/.bashrc \
    && echo 'export BUNDLE_APP_CONFIG=/workspaces/project/backend/.bundle' >> ~/.bashrc \
    && echo "mkdir -p ~/.bundle && touch ~/.bundle/config" >> ~/.bashrc \
    && echo "mkdir -p /workspaces/project/backend/.bundle && touch /workspaces/project/backend/.bundle/config" >> ~/.bashrc \
    && echo 'sudo chown -R vscode:vscode ~' >> ~/.bashrc \
    && echo 'sudo chown -R vscode:vscode /workspaces/project/backend' >> ~/.bashrc \
    && bundle config set path /workspaces/project/backend/vendor/bundle

WORKDIR /workspaces/project

COPY build/thecore.vsix /etc/thecore/
