version: "3.9"

services:
  proxy:
    image: marcnuri/port-forward:latest
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${BACKEND_DOMAIN}
      LETSENCRYPT_HOST: ${BACKEND_DOMAIN}
      REMOTE_HOST: backend
      REMOTE_PORT: 3000
    ports:
      - 80
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - internal
      - webproxy
  db:
    networks:
        - internal
  cache:
    networks:
        - internal
  backend:
    networks:
        - internal
  worker:
    networks:
        - internal

# This network is fixed to webproxy since is the name used in
# our production environments for the nginx-proxy docker image
# this way it can pickup the new rails app automatically and proxy it
# via http(s)
networks:
  internal:
  webproxy:
    name: webproxy
    external: true
