version: "3.7"

# These come from exported environment variables
# probably set in the shell script which handles 
# the up of the application.
x-vars: &vars
  # Hardcoded
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_RELATIVE_URL_ROOT: /
  RAILS_SERVE_STATIC_FILES: "true"
  REDIS_URL: redis://${COMPOSE_PROJECT_NAME}_store_1
  DATABASE_URL: postgres://postgres:postgres@${COMPOSE_PROJECT_NAME}_db_1/postgres?pool=${DATABASE_POOL:-30}
  ALLOW_MULTISESSIONS: "true"
  # Environment
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  APP_NAME: ${APP_NAME}
  COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  BASE_DOMAIN: ${BASE_DOMAIN}
  FE_SUBDOMAIN: ${FE_SUBDOMAIN}
  BE_SUBDOMAIN: ${BE_SUBDOMAIN}
  LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  LANG: ${LANG}
  BACKEND_DOMAIN: ${BE_SUBDOMAIN}.${BASE_DOMAIN}
  BACKEND_URL: https://${BE_SUBDOMAIN}.${BASE_DOMAIN}
  FRONTEND_DOMAIN: ${FE_SUBDOMAIN}.${BASE_DOMAIN}
  FRONTEND_URL: https://${FE_SUBDOMAIN}.${BASE_DOMAIN}

services: 
  db:
    image: postgres:latest
    restart: unless-stopped
    hostname: ${COMPOSE_PROJECT_NAME}_db_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck: 
      interval: 1s
      retries: 30
      test: "pg_isready -U postgres"
      timeout: 3s

  store:
    image: redis:latest
    entrypoint: "redis-server --appendonly yes"
    hostname: ${COMPOSE_PROJECT_NAME}_store_1
    restart: unless-stopped
    healthcheck: 
      interval: 1s
      retries: 30
      test: "redis-cli ping"
      timeout: 3s

  backend:
    image: ${IMAGE_TAG_BACKEND}
    restart: unless-stopped
    hostname: ${COMPOSE_PROJECT_NAME}_backend_1
    depends_on:
      - db
      - store
    entrypoint: /bin/thecore/entrypoint.sh
    environment:
      <<: *vars
      VIRTUAL_HOST: ${BE_SUBDOMAIN}.${BASE_DOMAIN}
      LETSENCRYPT_HOST: ${BE_SUBDOMAIN}.${BASE_DOMAIN}
      VIRTUAL_PORT: 3000
      HTTPS_METHOD: noredirect
    volumes:
      - /root/persistence/${COMPOSE_PROJECT_NAME}/storage:/app/storage
      - /root/persistence/${COMPOSE_PROJECT_NAME}/imports:/app/tmp/imports
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl --fail http://localhost:3000/}"
      interval: "60s"
      timeout: "3s"
      retries: 3

  backend-sidekiq:
    image: ${IMAGE_TAG_BACKEND}
    restart: unless-stopped
    hostname: ${COMPOSE_PROJECT_NAME}_sidekiq_1
    depends_on:
      - db
      - store
      - backend
    entrypoint: /bin/thecore/entrypoint-sidekiq.sh
    environment:
      <<: *vars
    volumes:
      - /root/persistence/${COMPOSE_PROJECT_NAME}/storage:/app/storage
      - /root/persistence/${COMPOSE_PROJECT_NAME}/imports:/app/tmp/imports
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-bundle exec sidekiqmon|grep $(hostname)}"
      interval: "60s"
      timeout: "3s"
      retries: 3
