#!/bin/bash

if ! [ -d ../dependencies ]
then
  echo "ERROR! This must be run from inside app directory and have a sibling directory called dependencies"
  exit 1  
fi

for i in *.gemspec
do
  if [[ -f "$i" ]]
  then
    echo -e "\e[31mThis folder contains a gemspec file, please run this script outside a rails engine project.\e[0m"
    exit 1
  fi
done

if ! [[ -f "Gemfile" ]]
then
  echo -e "\e[31mThis folder does not contain a Gemfile. Please run this script inside a Thecore App.\e[0m"
  exit 1
fi

# Trap failures to get also the line number of the failure
set -eE -o functrace
failure() {
  local lineno=$1
  local msg=$2
  echo "Failed at $lineno: $msg"
}
trap 'failure ${LINENO} "$BASH_COMMAND"' ERR

function ask_for_name # VARNAME prompt
{
  while [ -z "${!1}" ]
  do
    read -r -p "$2: " "$1"
  done
}

ask_for_name ENGINE_NAME "Please provide an engine name in underscore notation"
# Some sanity checks, allow only underscore names
pattern='^[a-z0-9_]+$'
if ! [[ "$ENGINE_NAME" =~ $pattern ]]
then
  echo -e "\e[31mError! Engine Name cannot contain special characters other than downcase letters, numbers and _\e[0m"
  exit 2
fi

# Asking for ENGINE specifications
ask_for_name ENGINE_AUTHOR "Please provide Engine's Author"
ask_for_name ENGINE_EMAIL "Please provide Engine's Author's Email"
ask_for_name ENGINE_HOMEPAGE "Please provide Engine's Homepage URL"
ask_for_name ENGINE_SUMMARY "Please provide Engine's Summary"
ask_for_name ENGINE_DESCRIPTION "Please provide Engine's Extended Description"
ask_for_name ENGINE_GEM_REPO "Please provide Engine's GEM repository"

# Sanity Checks on input variables
EMAIL_REGEX="^[a-z0-9!#\$%&'*+/=?^_\`{|}~-]+(\.[a-z0-9!#$%&'*+/=?^_\`{|}~-]+)*@([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z0-9]([a-z0-9-]*[a-z0-9])?\$"
if ! [[ $ENGINE_EMAIL =~ $EMAIL_REGEX ]]
then
  echo -e "\e[31mError! Engine Email must be a valid Email Address.\e[0m"
  exit 3
fi
if ! [[ $ENGINE_HOMEPAGE =~ https?://.* ]]
then
  echo -e "\e[31mError! Engine Homepage must be a valid URL.\e[0m"
  exit 2
fi
if ! [[ $ENGINE_GEM_REPO =~ https?://.* ]]
then
  echo -e "\e[31mError! Engine Gem Repo must be a valid URL.\e[0m"
  exit 4
fi

cd ../dependencies

rails plugin new "$ENGINE_NAME" -fG --full

cd "$ENGINE_NAME"

# Setup the gemspec file
function edit_gem_info # KEY VALUE FILE
{
  sed -i "/spec.${1}/d" "${3}".gemspec
  sed -i "/spec.version/a \ \ spec.${1} = $2" "${3}".gemspec
}
edit_gem_info homepage "\"$ENGINE_HOMEPAGE\"" "$ENGINE_NAME"
edit_gem_info authors "[\"$ENGINE_AUTHOR\"]" "$ENGINE_NAME"
edit_gem_info email "[\"$ENGINE_EMAIL\"]" "$ENGINE_NAME"
edit_gem_info summary "\"$ENGINE_SUMMARY\"" "$ENGINE_NAME"
edit_gem_info description "\"$ENGINE_DESCRIPTION\"" "$ENGINE_NAME"
edit_gem_info metadata "\"$ENGINE_DESCRIPTION\"" "$ENGINE_NAME"
sed -i "/spec.metadata/d" "${ENGINE_NAME}".gemspec
sed -i "/spec.respond_to?(:metadata)/a \ \ \ \ spec.metadata[\"allowed_push_host\"] = \"$ENGINE_GEM_REPO\"" "${ENGINE_NAME}".gemspec
# Remove all spec.add_dependency 
sed -i '/add_dependency/d' "${ENGINE_NAME}".gemspec
sed -i '/add_development_dependency/d' "${ENGINE_NAME}".gemspec

echo "Thecorizing Engine of type $TYPE"
thecore enhance engine ${TYPE}

# GIT
# Add gitignore
thecore utils add gitignore

# And manage working copy
git init
git config user.name "$ENGINE_AUTHOR"
git config user.email "$ENGINE_EMAIL"
git add . -A
git commit -a -m "Initial git"
git tag test0.1.0
echo "Please add a git repository URI if you like (empty string to add nothing):"
read -r URI
if [[ -z $URI ]]
then
    exit 0
fi

git remote add origin "$URI"
git push --set-upstream origin master
git push --tags

# cd ../../..

exit 0