#!/bin/bash

[[ $# -ne 1 ]] && echo -e "Please provide one argument, which must match and env.$argument file present on the disc.\ni.e. If a file named env.dev is present on the disc, the build command must be like:\n\n  build dev"

sudo env $(cat env.$1) docker-compose build