#!/bin/bash

if [ $# -eq 0 ]
then
  echo
  echo -e "\e[31mThe most common THECORE commands are:\e[0m"
  echo
  column /etc/thecore/templates/help -t -s '|' -e
  echo
else
  LAST="${@: -1}"
  BASEPATH="/usr/bin/thecore_modules"
  for PARAM in "$@"
  do
    if [[ $PARAM == $LAST ]]
    then
      $BASEPATH/$PARAM
      break
    else 
      BASEPATH="${BASEPATH}/$PARAM"
    fi 
  done
fi

exit 0