#!/bin/bash

# Trap failures to get also the line number of the failure
set -eE -o functrace
failure() {
  local lineno=$1
  local msg=$2
  echo "Failed at $lineno: $msg"
}
trap 'failure ${LINENO} "$BASH_COMMAND"' ERR

# Sanity Checks
for i in *.gemspec
do
  if ! [ -f "$i" ]
  then
    echo -e "\e[31mThe Folder $(pwd) does NOT contain a gemspec file, please run this script INSIDE a rails engine project.\e[0m"
    exit 1
  fi
done

# ASK for api only gem or UI dependent one and add a dependency on model_driven_api or thecore_ui_rails_admin respectively.
PS3="Please select the type of engine you are creating, select it by specifying element's number from the list above:"
TYPE="Both"
select T in "API" "GUI" "Both"
do
  echo "Selected ${T}"
  if [[ -n "${T}" ]]
  then
    TYPE="$T"
    break
  fi
done

ENGINE_NAME=$(cat -- *.gemspec|grep -e spec.name -e s.name|sed 's/^ *s.*.name *= *//'|sed 's/["]//g')
ENGINE_NAME_PASCAL_CASE=$(echo "${ENGINE_NAME}" | sed -r 's/(^|_)([a-z])/\U\2/g')

mkdir -p db/migrate app/models/concerns/api app/models/concerns/rails_admin config/initializers config/locales

touch db/migrate/.keep app/models/concerns/api/.keep app/models/concerns/rails_admin/.keep config/initializers/.keep config/locales/.keep

function prepare_for_dependency
{
  sed -i "/spec.files/a \ \ spec.add_dependency '${2}', '~> 2.0'" "${1}".gemspec
  sed -i "/require .${2}./d" lib/"${1}".rb
  sed -i "1 s/^/require '${2}'\n/" lib/"${1}".rb
}
case $TYPE in
  "API")
  prepare_for_dependency "${ENGINE_NAME}" "model_driven_api"
  ;;
  "GUI")
  prepare_for_dependency "${ENGINE_NAME}" "thecore_ui_rails_admin"
  ;;
  "Both")
  prepare_for_dependency "${ENGINE_NAME}" "model_driven_api"
  prepare_for_dependency "${ENGINE_NAME}" "thecore_ui_rails_admin"
  ;;
esac

# Adding auto migrate to engine.rb
cat > lib/"${ENGINE_NAME}"/engine.rb << EOL
module ${ENGINE_NAME_PASCAL_CASE}
  class Engine < ::Rails::Engine
    initializer "${ENGINE_NAME}.assets.precompile" do |app|    
      # Here you can place the assets provided by this engine in order for them to be precompiled in production and JIT 
      # compiled in development.
      # As an example:
      # app.config.assets.precompile += %w( overrides.css )
      # app.config.assets.precompile += %w( android-chrome-192x192.png )
      # ...
    end
    initializer '${ENGINE_NAME}.add_to_thecore_engines_list' do |app|
      Thecore::Base.thecore_engines << self.class
    end
    initializer '${ENGINE_NAME}.add_to_migrations' do |app|
      # Automatically add to main app migrations coming from this engine withiut the need for a rake install
      config.paths['db/migrate'].expanded.each { |expanded_path| app.config.paths['db/migrate'] << expanded_path } unless app.root.to_s.match root.to_s
    end
  end
end
EOL

# Adding auto migrate to engine.rb
if [ ! -f config/initializers/abilities_for_"${ENGINE_NAME}".rb ]
then
cat > config/initializers/abilities_for_"${ENGINE_NAME}".rb << EOL
module Abilities
  class ${ENGINE_NAME_PASCAL_CASE}
    include CanCan::Ability
    def initialize user
      # # By default only admin can do everything
      # # Here are example of usage
      # if user && !user.admin? && user.has_role?(:operator)
      #   # a specific role, brings specific powers
      #   cannot :manage, :all
      #   can :access, :rails_admin # grant access to rails_admin
      # end
      # # Root actions must be declared like this:
      # if user && user.admin?
      #   can :name_of_root_action, :all
      # end
    end
  end
end
EOL
fi

# Replace static VERSION with git tag based version
sed -i 's/^  VERSION =.*/  VERSION = "#{`git describe --tags $(git rev-list --tags --max-count=1)`}"/' lib/"$ENGINE_NAME"/version.rb

# Adding after initialize
cat > config/initializers/after_initialize_for_"${ENGINE_NAME}".rb << EOL
Rails.application.configure do
  config.after_initialize do
    # Good place for sending concerns about modules
    # i.e.
    # ModelName.send(:include, ModelNameConcern)
    # - ModelNameConcern can be defined in config/initializers folder in order to be sure it's automatically loaded during engine bootstrap
  end
end
EOL

# Adding after locales
cat > config/locales/it."${ENGINE_NAME}".yml << EOL
it:
  activerecord:
    models:
    attributes:
EOL

cat > config/locales/en."${ENGINE_NAME}".yml << EOL
en:
  activerecord:
    models:
    attributes:
EOL

# For generating models and the likes, in the local, from gem perspective, add sqlite as dependency
grep sqlite3 Gemfile || echo "gem 'sqlite3'" >> Gemfile

# Add CI CD Automation
# GITLAB
cat > .gitlab-ci.yml << EOL
image: gabrieletassoni/vscode-devcontainers-thecore:2

variables:
    GITLAB_EMAIL: ""
    GITLAB_USER_NAME: ""
    GITLAB_OAUTH_TARGET: ""
    GITLAB_GEM_REPO_TARGET: ""

stages:
    - build
    - release

build_gem:
    rules:
        - if: \$CI_COMMIT_TAG
          when: never 
        - when: always
    stage: build
    script:
        - /usr/bin/gem-compile.sh

EOL

# GITHUB
mkdir -p .github/workflows/
cat > .github/workflows/gempush.yml << EOL
name: Ruby Gem

on: push

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Check the version if it already exists as a tag, if so set a variable to use as a condition in order 
    # to skip next steps without failing the job, using Env File to store the variable
    - name: Check if version already exists
      id: check_version
      run: |
        version=\$(grep -oP 'VERSION = "\K[^"]+' lib/*/version.rb | awk -F'.' '{print \$1"."\$2"."\$3}')
        git fetch --unshallow --tags
        echo \$?
        if git tag --list | grep -q \$version;
        then
          echo "Version \$version already exists"
          echo "version_exists=true" >> "\$GITHUB_ENV"
        else
          echo "Version \$version does not exist"
          echo "version_exists=false" >> "\$GITHUB_ENV"
        fi
    # If the version already exists, skip the next steps
    - uses: ruby/setup-ruby@v1
      if: env.version_exists == 'false'
      with:
        ruby-version: '3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # sets the git tag to the same version as the gem
    - name: Set git tag
      if: env.version_exists == 'false'
      run: |
        git config --local user.email "noreply@alchemic.it"
        git config --local user.name "AlchemicIT"
        version=\$(grep -oP 'VERSION = "\K[^"]+' lib/*/version.rb | awk -F'.' '{print \$1"."\$2"."\$3}')
        git tag -a \$version -m "Version \$version"
        git push --tags
        
    - name: Publish to RubyGems
      if: env.version_exists == 'false'
      run: |
        mkdir -p \$HOME/.gem
        touch \$HOME/.gem/credentials
        chmod 0600 \$HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: \${GEM_HOST_API_KEY}\n" > \$HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: \${{secrets.RUBYGEMS_AUTH_TOKEN}}
EOL

exit 0